### PR TITLE
WIP: Travis integration

### PR DESCRIPTION
**Pull request by AronNovak**
for coding standard

### CODE REVIEW

**Comment by AronNovak** [comment]
The current error:
image

Afterwards phpsniffer should check the custom code in the repository.

**Comment by AronNovak** [comment]
ported from https://github.com/Gizra/drupal-elm-starter

**Comment by mhavelant** [comment]
Thanks!

**Comment by AronNovak** [comment]
@mhavelant actually it does not successfully work, the error at https://github.com/brainsum/qashot/pull/22#issuecomment-321826819 still needs to be resolved.

**Comment by mhavelant** [comment]
I fixed it in the docker_update branch.

**Pull request merged**
